### ISSUE TITLE
uninitialized constant ActiveModel::Serializers::Xml

### ISSUE THREAD

**Issue by tit** [ThomasAlxDmy/Exodus#11]
I installed this gem, but can not required this.

My environment:
```bash
$ gem install exodus
Successfully installed exodus-1.1.7
Parsing documentation for exodus-1.1.7
Done installing documentation for exodus after 0 seconds
1 gem installed
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
$ rvm --version
rvm 1.29.8-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ irb --version
irb 0.9.6(09/06/30)
$ gem --version
2.7.9
$ gem list mongo

*** LOCAL GEMS ***

mongo (2.8.0, 1.12.5)
mongo_mapper (0.14.0)
mongoid (7.0.2)
```

```bash
$ irb -r exodus
Traceback (most recent call last):
	25: from /Users/tit/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
	24: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:376:in `start'
	23: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/init.rb:21:in `setup'
	22: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/init.rb:276:in `load_modules'
	21: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/init.rb:276:in `each'
	20: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/init.rb:278:in `block in load_modules'
	19: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	18: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	17: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	16: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/exodus-1.1.7/lib/exodus.rb:4:in `<top (required)>'
	15: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	14: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	13: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/exodus-1.1.7/lib/exodus/migrations/migration.rb:1:in `<top (required)>'
	12: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/exodus-1.1.7/lib/exodus/migrations/migration.rb:2:in `<module:Exodus>'
	11: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/exodus-1.1.7/lib/exodus/migrations/migration.rb:3:in `<class:Migration>'
	10: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 9: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 8: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/document.rb:2:in `<top (required)>'
	 7: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/document.rb:3:in `<module:MongoMapper>'
	 6: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/document.rb:7:in `<module:Document>'
	 5: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 4: from /Users/tit/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 3: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/plugins/active_model.rb:2:in `<top (required)>'
	 2: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/plugins/active_model.rb:3:in `<module:MongoMapper>'
	 1: from /Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/plugins/active_model.rb:4:in `<module:Plugins>'
/Users/tit/.rvm/gems/ruby-2.5.1/gems/mongo_mapper-0.14.0/lib/mongo_mapper/plugins/active_model.rb:9:in `<module:ActiveModel>': uninitialized constant ActiveModel::Serializers::Xml (NameError)
```

What would you recommend?

**Comment by tit** [comment]
I fix it by https://github.com/rails/rails/issues/24558#issuecomment-210407407

```
require 'activemodel-serializers-xml'
require 'exodus'
```

That is work for me.
